default_task_args:
    - -ldflags
    - "-X github.com/rafaelmartins/filebin/internal/version.Version={{.Version}}"

targets:
    distcheck:
        task_args:
            - ./...
    static-dist-linux-amd64:
        task_script: build-aux/build-static.sh
