name: yatr
on:
  - push

jobs:
  yatr:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        target:
          - distcheck

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run yatr
        env:
          CGO_ENABLED: "1"
          TARGET: "${{ matrix.target }}"
          DISTFILES_URL: "${{ secrets.DISTFILES_URL }}"
        run: curl -sSf https://yatr.rgm.io/run.sh | bash
